tuto_app/config/routes.rb
Rails.application.routes.draw do
    root "pages#top"

  get 'sessions/new'
  resources :users
  get 'users/new'
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    

end

tuto_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tuto_app/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

tuto_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tuto_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
  def about
  end
end

tuto_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
        include SessionsHelper
  def new
  end
  def create
      user = User.find_by(email: params[:session][:email])

      if user && user.authenticate(params[:session] [:password])

        login(user)
        redirect_to root_url
      else
        render "new"

  end
 end
    
  def destroy
      logout
      redirect_to root_url
  end
  
end

tuto_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end
  
  def create
      @user = User.new(user_params)
      if @user.save
        redirect_to root_url
      end
    end
    
   def edit
        @user = User.find(params[:id])
   end
   
   def update
       @user = User.find(params[:id])
       if @user.update_attributes(user_params)
           redirect_to root_url
        else
           render 'edit'
        end
    end
  
  private
        def user_params
            params.require(:user).permit(:name, :email, :password,:password_confirmation)
        end
    
end

tuto_app/app/helpers/application_helper.rb
module ApplicationHelper
end

tuto_app/app/helpers/pages_helper.rb
module PagesHelper
end

tuto_app/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def log_out
        session.delete(:user_id)
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    


end    

tuto_app/app/helpers/users_helper.rb
module UsersHelper
end

tuto_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link_rel="stylesheet" type="text/css"
          href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="header">
          <div class="headerLeft">
             <h1 class="headerLogo">TutoApp</h1>
             <ul class="headerNav">
                 
                 <li><%= link_to "Home", root_url %></li>
                 <li><%= link_to "about", about_path %></li>
             </ul>
        　</div>
        　<div class="headerRight">
        　    
        　   <% if current_user %>
        　   
        　        <%= current_user.name %>
        　        
        　   <% else %>
        　   
        　   <%=link_to "新規登録", new_user_path%>
             <%=link_to "ログイン", login_path%>
             
             <% end %>
          </div>
      </header>
    <%= yield %>
  </body>
</html>

tuto_app/app/views/pages/abouut.html.erb
about

tuto_app/app/views/pages/top.html.erb
<h1>Pages#top</h1>
<p>Find me in app/views/pages/top.html.erb</p>

tuto_app/app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "アカウントを作成する" %>
<% end %>

tuto_app/app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
      <%= f.label :name, "ユーザー名" %>
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワードの確認" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "アカウントを作成する" %>
<% end %>